const cat = {
  tvAndAudio: 'tvAndAudio',
  tvBox: 'tvBox',
  powerTools: 'powerTools',
  headphones: 'headphones',
  cellPhones: 'cellPhones',
  smartWatches: 'smartWatches',
  gameAndVideo: 'gameAndVideo',
  robotClean: 'robotClean',
  sportWatches: 'sportWatches',
  tablets: 'tablets',
  computersAndLaptop: 'computersAndLaptop',
  camerasAndPhotos: 'camerasAndPhotos',
};

export const categories = [
  {
    _id: 1001,
    name: 'TV & Audio',
    image: 'https://i.ibb.co/yFw3VLdF/tv-audio.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'tvAndAudio',
  },
  {
    _id: 1002,
    name: 'TV Box',
    image: 'https://i.ibb.co/WWbGDVTb/tv-box.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'tvBox',
  },
  {
    _id: 1003,
    name: 'Power Tools',
    image: 'https://i.ibb.co/xq60gW9k/power-tools.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'powerTools',
  },
  {
    _id: 1004,
    name: 'Headphones',
    image: 'https://i.ibb.co/nMtDKNSQ/headphones.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'headphones',
  },
  {
    _id: 1005,
    name: 'Cell Phones',
    image: 'https://i.ibb.co/JW17LBJK/phones.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'cellPhones',
  },
  {
    _id: 1006,
    name: 'Smart Watches',
    image: 'https://i.ibb.co/q34wNHFp/smart-watch.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'smartWatches',
  },
  {
    _id: 1007,
    name: 'Game & Video',
    image: 'https://i.ibb.co/pr1CyVGH/game-controller.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'gameAndVideo',
  },
  {
    _id: 1008,
    name: 'Robot Clean',
    image: 'https://i.ibb.co/R4VrPgN9/robot-clean.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'robotClean',
  },
  {
    _id: 1009,
    name: 'Sport Watches',
    image: 'https://i.ibb.co/GvZrDp2p/sport-watch.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'sportWatches',
  },
  {
    _id: 1010,
    name: 'Tablets',
    image: 'https://i.ibb.co/0p9kSQxN/tablet.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'tablets',
  },
  {
    _id: 1011,
    name: 'Computers & Laptops',
    image: 'https://i.ibb.co/Xk4kjBYn/laptop.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'computersAndLaptop',
  },
  {
    _id: 1012,
    name: 'Cameras & Photos',
    image: 'https://i.ibb.co/Zzrr3g1y/camera.png',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.',
    _base: 'camerasAndPhotos',
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    image: 'https://i.ibb.co/tp1vgJb9/h1.webp',
    _base: '/products?active=computersAndLaptop',
  },
  {
    _id: 3002,
    image: 'https://i.ibb.co/Z1g4fyd7/h2.webp',
    _base: '/products?active=tvAndAudio',
  },
];

export const products = [
  {
    _id: 2001,
    name: 'Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band',
    images: [
      'https://i.ibb.co/gZ0w79jm/1330839446.webp',
      'https://i.ibb.co/bRDJXZZk/1330739446.webp',
      'https://i.ibb.co/0R8fy02G/1330939446.webp',
      'https://i.ibb.co/zTpt9511/1331039446.webp',
      'https://i.ibb.co/XGMYsfV/1331139446.webp',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 250,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.8,
    reviews: 80,
    category: 'Smart Watches',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Samsung',
    isStock: true,
    overView: 'Smart health watch',
    isNew: false,
    _base: cat?.smartWatches,
  },
  {
    _id: 2003,
    name: 'Garmin 010-02626-10 Instinct 2, Rugged Outdoor Watch with GPS, Built for All Elements, Multi-GNSS Support, Tracback Routing and More',
    images: [
      'https://i.ibb.co/Q3yFtzKm/51-Kzbb-K46c-L-AC-SX569.jpg',
      'https://i.ibb.co/mr8nt2pr/51-HRC7y-Kd-LL-AC-SX569.jpg',
      'https://i.ibb.co/hpSbqnY/51y-JBk-Xe-Hk-L-AC-SX569.jpg',
      'https://i.ibb.co/cq7Qqs2/510-Tvk-Pn-Ew-L-AC-SX569.jpg',
      'https://i.ibb.co/whRBmDWH/518u-Ieo-U6r-L-AC-SX569.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 650,
    discountedPrice: 570,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: 'Sport Watches',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'MI Exclusive',
    isStock: true,
    overView: 'Smart health watch',
    isNew: true,
    _base: cat?.sportWatches,
  },
  {
    _id: 2004,
    name: 'KODAK PIXPRO AZ405-BK 20MP Digital Camera 40X Optical Zoom 24mm Wide Angle Lens Optical Image Stabilization 1080P Full HD Video 3" LCD Vlogging Camera',
    images: [
      'https://i.ibb.co/dhqBxS8/81-C9-A0-E-8-TL-AC-SX425.jpg',
      'https://i.ibb.co/zHPxcTkV/81b-Wylee-XXL-AC-SX425.jpg',
      'https://i.ibb.co/vx0LkwNv/81-Cw-Tmrgy-VL-AC-SX425.jpg',
      'https://i.ibb.co/cKbCf2hJ/81s6v-B6op-OL-AC-SX425.jpg',
      'https://i.ibb.co/CsPH4ddg/810-Tf-XCYg-TL-AC-SL1500.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 440,
    discountedPrice: 380,
    quantity: 1,
    rating: 4.2,
    reviews: 120,
    category: 'Camera & Photos',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: false,
    overView: 'Cameras & Photos',
    isNew: false,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 2005,
    name: 'Bose TV Speaker - Soundbar for TV with Bluetooth and HDMI-ARC Connectivity, Black, Includes Remote Control',
    images: [
      'https://i.ibb.co/1JMSg3Xx/41-Nl-g-N2hv-L-AC-SX425.jpg',
      'https://i.ibb.co/R4jF2hLM/51d4r-IH3-PGL-AC-SX425.jpg',
      'https://i.ibb.co/jv9SgJ5M/51de3-TB8-F3-L-AC-SX425.jpg',
      'https://i.ibb.co/0j11Vv6L/51-OTwt0tn-CL-AC-SX425.jpg',
      'https://i.ibb.co/mVTzJgzZ/61ps-Qc-In-Ij-L-AC-SX425.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 449,
    discountedPrice: 278,
    quantity: 10,
    rating: 4.2,
    reviews: 20,
    category: 'TV & Audio',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Bose',
    isStock: true,
    overView: 'Blutooth Speaker',
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2007,
    name: 'Apple AirPods Max Wireless Over-Ear Headphones with AppleCare+ (2 Years)',
    images: [
      'https://i.ibb.co/bjHM1pqz/81-If-N-Rw8u-L-AC-SX425.jpg',
      'https://i.ibb.co/6Jy1QGj9/61zk-Xd64-WL-AC-SX425.jpg',
      'https://i.ibb.co/Nn1vx3p8/718-DYLue-B-L-AC-SX425.jpg',
      'https://i.ibb.co/W40hwcV0/915jk-Z40k-SL-AC-SX425.jpg',
      'https://i.ibb.co/Q7MLt18n/71-GVJl7zfq-L-AC-SX425.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 600,
    discountedPrice: 550,
    quantity: 1,
    rating: 4,
    reviews: 60,
    category: 'Headphones & Speakers',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Headphones',
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2008,
    name: 'Apple 2025 MacBook Air 13-inch Laptop with M4 chip: Built for Apple Intelligence, 13.6-inch Liquid Retina Display, 16GB Unified Memory, 256GB SSD Storage, 12MP Center Stage Camera, Touch ID;',
    images: [
      'https://i.ibb.co/3m3TYDwm/712dp0y-Ayd-L-AC-SX425.jpg',
      'https://i.ibb.co/hJVQvL2f/71-PUa-DG0-FL-AC-SX425.jpg',
      'https://i.ibb.co/VW7QyPzw/81-VE3-E8cgl-L-AC-SX425.jpg',
      'https://i.ibb.co/TqFsq9rb/61d-HNAMoi-FL-AC-SL1500.jpg',
      'https://i.ibb.co/qMHtmLD5/61-UGymu-PNHL-AC-SL1500.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 1160,
    discountedPrice: 1080,
    quantity: 1,
    rating: 4.7,
    reviews: 190,
    category: 'Computers & Laptops',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Computers & Laptops',
    isNew: false,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 2009,
    name: 'Shark AI Ultra Voice Control Robot Vacuum with Matrix Clean Navigation, Home Mapping, 60-Day Capacity, XL Self-Empty Base for Homes with Pets, Carpet & Hard Floors',
    images: [
      'https://i.ibb.co/qMB2V6qS/61y-Q2hur-PL-AC-SX569.jpg',
      'https://i.ibb.co/VcYLj2jy/614syadu96-L-AC-SX569.jpg',
      'https://i.ibb.co/BHvgVBS0/81p-RSb-q0a-L-AC-SX569.jpg',
      'https://i.ibb.co/cKzLkBnt/719-Itk5-Pin-L-AC-SX569.jpg',
      'https://i.ibb.co/jPwSrPpq/71-HFWi-LJmm-L-AC-SX569.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 450,
    discountedPrice: 380,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: 'Robot Clean',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Robot Clean',
    isNew: true,
    _base: cat?.robotClean,
  },
  {
    _id: 2010,
    name: 'Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone',
    images: [
      'https://i.ibb.co/MxtJNHm5/71-KGk-Q-KOKL-AC-SL1500.jpg',
      'https://i.ibb.co/G4jb6dHH/71-VVllu-Eij-L-AC-SL1500.jpg',
      'https://i.ibb.co/Tq48pFHd/71yh1-Sfyg-ML-AC-SL1500.jpg',
      'https://i.ibb.co/nNsk1bwg/71-IXcy-AXC8-L-AC-SL1500.jpg',
      'https://i.ibb.co/6JPJJWhh/81-BHHupp-E9-L-AC-SL1500.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 305,
    discountedPrice: 285,
    quantity: 1,
    rating: 4.1,
    reviews: 160,
    category: 'Cell Phones',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Cell Phones',
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 2012,
    name: 'BLACK+DECKER 20V MAX* POWERCONNECT Cordless Drill Kit + 100 pc. Kit (BDC120VA100)',
    images: [
      'https://i.ibb.co/bj8jtppG/71-V7um-5p4-L-AC-SX522.jpg',
      'https://i.ibb.co/C3zdVZB3/417-TFvp-UPGL-AC.jpg',
      'https://i.ibb.co/67FycYLp/71a-Sb-Jxgdd-L-AC-SX522.jpg',
      'https://i.ibb.co/PsTRMSMJ/515-GMg1-Vk8-L-AC.jpg',
      'https://i.ibb.co/mrzSSb4G/61ca-D-YFRWL-AC-SL1000.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 150,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.7,
    reviews: 90,
    category: 'Power Tools',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Power Tools',
    isNew: true,
    _base: cat?.powerTools,
  },
  {
    _id: 2013,
    name: 'Digital Converter, Ematic Digital TV Converter Box with Recording, Playback, & Parental Controls',
    images: [
      'https://i.ibb.co/CKNBBfg8/51v-F-Z8-U2v-L-AC-SX425.jpg',
      'https://i.ibb.co/PGwvdfzF/51d-A9-FHrq-OL-AC-SX425.jpg',
      'https://i.ibb.co/7tfTkMjk/71wi-Lj-Iy-Ti-L-AC-SX425.jpg',
      'https://i.ibb.co/xKymHVKw/31-ZIPVBZz-IL-AC.jpg',
      'https://i.ibb.co/hRBd02Dk/41w-IHPFt-Jz-L-AC.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 479,
    discountedPrice: 399,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: 'TV Box',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'TV Box',
    isNew: true,
    _base: cat?.tvBox,
  },
  {
    _id: 2014,
    name: 'PlayStation DualSense® Wireless Controller',
    images: [
      'https://i.ibb.co/v4dcC9BG/61-WRPy-QAIIL-SX522.jpg',
      'https://i.ibb.co/bMnFXbLZ/6117-Ss-HEKIL-SX522.jpg',
      'https://i.ibb.co/Z1JhnJwx/61-O-q-EOU7-NL-SX522.jpg',
      'https://i.ibb.co/LXLK61G6/61-Jr-YNgkv-L-SX522.jpg',
      'https://i.ibb.co/whNfHN5J/51-TSGh-Afvo-L-SX522.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 100,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.2,
    reviews: 110,
    category: 'Game and Video',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Game & Video',
    isNew: true,
    _base: cat?.gameAndVideo,
  },
  {
    _id: 2018,
    name: 'Samsung Galaxy Tab A9+ Plus 11” 64GB Android Tablet, Big Screen, Quad Speakers, Upgraded Chipset, Multi Window Display, Slim, Light, Durable, Kids Friendly Design, US Version, 2024',
    images: [
      'https://i.ibb.co/932q6VK9/61h-qe-D-qf-L-AC-SX425.jpg',
      'https://i.ibb.co/WWbZdXG7/51lc-Pk-Db-So-L-AC-SX425.jpg',
      'https://i.ibb.co/7dCBsKS1/61-5-FEK8l8-L-AC-SX425.jpg',
      'https://i.ibb.co/gMTR5V4s/71-P2kt9xap-L-AC-SX425.jpg',
      'https://i.ibb.co/6JN4kH61/81y-ND3mzm-AL-AC-SX425.jpg',
    ],
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.',
    regularPrice: 350,
    discountedPrice: 330,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: 'Tablets',
    colors: ['red', 'blue', 'green', 'yellow', 'black', 'white'],
    brand: 'Lorem ipsum dolor sit',
    isStock: true,
    overView: 'Tablets',
    isNew: true,
    _base: cat?.tablets,
  },
];
